### ISSUE TITLE
Add 'same' keyword 

### ISSUE THREAD

**Issue by ccmywish** [cryptic-less/cr#1]
When facing the same meaning of two words, we should keep the SPOT principle.

For example, JPEG and JPG should point to only one descrptions rather than two duplicates.

So I'll add a keyword 'same' as the solution like below:

```toml
[JPEG]
desc = "a image format"
full = "blah blah"

[JPG]
same = "JPEG" # As it may be same as many words, but should be single point, so do not use array
```
