### ISSUE TITLE
Add 'see' keyword

### ISSUE THREAD

**Issue by ccmywish** [cryptic-less/cr#2]
When two words are related, for example `ICO` and `CUR` format, it's good to notice user of each anther. 

So I'll add a keyword `see` for the solution, as like `see also` in man page. 

```toml
[ICO]
desc = "a icon image format for Windows"
see = ["CUR"]

[CUR]
desc = "a cursor image format for Windows"
see = ["ICO"]
```
